server:  
  port: ${PORT:8082}

logging:
  level:
    org.springframework.security: DEBUG
    root: debug
    web: debug

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      
security:
  oauth2:
    client:
      client-id: account
      client-secret: secret
      scope: read
      access-token-uri: http://10.128.249.89:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
    resource:
      token-info-uri: http://10.128.249.89:9999/oauth/check_token