server:  
  port: ${PORT:8082}

spring:  
  application:
    name: account-service

logging:
  level:
    org.springframework.security: DEBUG
    root: debug
    web: debug
      
security:
  user:
    password: none
  oauth2:
    client:
      client-id: account-service
      client-secret: secret
      scope: read
      access-token-uri: http://10.128.249.89:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
    resource:
      token-info-uri: http://10.128.249.89:9999/oauth/check_token