server:  
  port: ${PORT:8765}

spring:  
  application:
    name: gateway-server
  datasource:
    url: jdbc:postgresql://10.128.249.89:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
      
zuul:
  ignoredServices: '*'
  routes:
    auth-server:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server
    account:
      path: /account/**
      sensitiveHeaders: 
      serviceId: account-service
      
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://10.128.249.89:8761/eureka/