server:  
  port: ${PORT:9999}

spring:  
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    schema: classpath:/script/schema.sql
    data: classpath:/script/data.sql

    
logging:
  level:
    org.springframework.security: DEBUG
    root: debug
    web: debug

auth-service:
  hostname: localhost
  port: 8080
  contextPath: /uaa